package pl.publicprojects.predictor.model.data.container;

import lombok.Getter;
import lombok.Setter;
import org.nd4j.linalg.api.ndarray.INDArray;
import pl.publicprojects.language.interpreter.Interpreter;
import pl.publicprojects.language.interpreter.data.math.LanguageNumber;
import pl.publicprojects.language.interpreter.data.math.number.numbers.DoubleNumber;
import pl.publicprojects.language.interpreter.data.math.number.numbers.DoubleVectorNumber;
import pl.publicprojects.language.interpreter.data.types.VariableData;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * Class for store expressions that will treat as new parameters in DataLineContainers
 * (VirtualDataLineContainer and StandardDataLineContainer)
 * For example when we have data with columns [x, y], after add new expression exp1 here
 * columns of this table will have a following form: [x, y, exp1]
 */
@Getter
public class ProxyDataLineContainer {

    private final Interpreter interpreter;
    /**
    * List of expressions generated by ExpressGraphGenerator and high-scored by model
    */
    private final List<byte[]> expressionList = new ArrayList<>();

    /**
    * List of variables that we work with to evaluate values of expressions
    */
    @Setter
    private List<VariableData> variables;

    public ProxyDataLineContainer(Interpreter interpreter) {
        this.interpreter = interpreter;
    }

    /**
    * Method for evaluate value by Interpreter
    *
    * @param index That's index of expressions list
    */
    public LanguageNumber<?> getValue(int index) throws IOException {
        byte[] expression = expressionList.get(index);

        Object resultValue = interpreter.getAlgebraicExpressionManager()
                .getResult(expression)
                .getValue();

        if(resultValue instanceof Double resultDoubleValue)
            return new DoubleNumber(resultDoubleValue);
        if(resultValue instanceof INDArray arr) {
            return new DoubleVectorNumber(arr);
        }
        throw new RuntimeException("Unsupported type: " + resultValue.getClass().getSimpleName());
    }

}
