package pl.publicprojects.predictor.model.data;

import lombok.Getter;
import lombok.Setter;
import pl.publicprojects.language.interpreter.Interpreter;
import pl.publicprojects.language.interpreter.data.math.LanguageNumber;
import pl.publicprojects.language.interpreter.data.math.number.numbers.DoubleNumber;
import pl.publicprojects.language.interpreter.data.types.VariableData;

import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

@Getter
public class ProxyDataContainer {

    private final Interpreter interpreter;
    /*
    * List of expressions generated by ExpressGraphGenerator and high-scored by model
    * */
    private final List<byte[]> expressionList = new ArrayList<>();

    /*
    * List of variables that we work with to evaluate values of expressions
    * */
    @Setter
    private List<VariableData> variables;

    public ProxyDataContainer(Interpreter interpreter) {
        this.interpreter = interpreter;
    }

    /*
    * Method for evaluate value by Interpreter
    * @param index That's index of expressions list
    * */
    public LanguageNumber<?> getValue(DataContainer container, int index) throws IOException {
        byte[] expression = expressionList.get(index);

        double resultDoubleValue = (double) interpreter.getAlgebraicExpressionManager()
                .getResult(expression)
                .getValue();

        return new DoubleNumber(resultDoubleValue);
    }

}
